name: CI

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        rust: ["1.64", stable]
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{matrix.rust}}
    - run: cargo test --workspace --all-targets
    - run: cargo test --workspace --doc

  clippy:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@1.68
      with:
        components: clippy
    - run: cargo clippy --workspace --all-features --all-targets -- -D warnings

  rustfmt:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - run: cargo fmt --check --all
